---
- name: task2
  hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: Add the users
    when: 
    - ansible_facts['distribution'] == "Ubuntu" 
    - ansible_facts['distribution_version'] == "16.04"
    ansible.builtin.user:
      name: "{{ item }}"
      group: devops
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
    with_items:
    - Bob
    - ben
    - lisa
    - katty
    - tom

  - name: Ensure group "devops" exists
    when: 
    - ansible_facts['distribution'] == "Ubuntu" 
    - ansible_facts['distribution_version'] == "16.04"
    ansible.builtin.group:
      name: devops
      state: present

  - name: Install wordpress
    hosts: all
    become: true
    become_method: sudo
    vars:
      wordpress_version: "4.0.32"
      php_version: "5.4.16"
    
  - name: Information
    when: 
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == "16.04"
    ansible.builtin.debug:
      var: ansible_facts['distribution_version']

  - name: Installing Telnet
    when: 
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == "16.04"
    ansible.builtin.package:
      name: telnet
      state: present

  - name: Installing apache2
    when: 
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == "16.04"
    ansible.builtin.package:
      name: apache2
      state: present
    
    
  - name: Get wordpress 
    when: 
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == "16.04"
    get_url:
      url: https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz
      dest: /tmp/wordpress-{{ wordpress_version }}.tar.gz
      mode: '0440'