---
- name: task2
  hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: Add the users
    when: 
    - ansible_facts['distribution'] == "Ubuntu" 
    - ansible_facts['distribution_version'] == "16.04"
    ansible.builtin.user:
      name: "{{ item }}"
      group: devops
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
    with_items:
    - Bob
    - ben
    - lisa
    - katty
    - tom

  - name: Ensure group "devops" exists
    when: 
    - ansible_facts['distribution'] == "Ubuntu" 
    - ansible_facts['distribution_version'] == "16.04"
    ansible.builtin.group:
      name: devops
      state: present