---
- name: Install wordpress
  hosts: all
  become: true
  become_method: sudo
  vars:
    wordpress_version: "4.0.32"
    php_version: "5.4.16"
  tasks: 
  - name: Information
    when: 
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == "16.04"
    ansible.builtin.debug:
      var: ansible_facts['distribution_version']

  - name: Installing Telnet
    when: 
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == "16.04"
    ansible.builtin.package:
      name: telnet
      state: present

  - name: Installing apache2
    when: 
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == "16.04"
    ansible.builtin.package:
      name: apache2
      state: present
    
    
  - name: Get wordpress 
    when: 
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == "16.04"
    get_url:
      url: https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz
      dest: /tmp/wordpress-{{ wordpress_version }}.tar.gz
      mode: '0440'